name: Red Panda Hacks
version: I # Could also be a roman numeral or other number, will be concatenated with the hackathon name where necessary
main_website: https://redpandahacks.com
dashboard_url: dashboard.redpandahacks.com
donotreply: donotreply@redpandahacks.com
contact_email: team@redpandahacks.com