# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1077de79cb9bb9ae1188e28154c892e7ecc04bd9a6e0264514bb148f34e28c6caf54d0b5c9388de66fcef04db5485c3672d41c6af4540b9c65fd82aeeb4c358

test:
  secret_key_base: 242f75594ec85a36c32535d6271241f8fb34c66a358104dd9daef5c86afd89eab473a24cc7d10260ca42d54f54aa080cb2bcad71a9bfb25915fa8616469d4b00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

slack: SL4CK_T0K3N